trigger:
- master
- release
- develop

jobs:
- job: JOB1
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo "Branch name - $(Build.SourceBranch)"
      echo "Build ID    - $(Build.BuildId)"

  - task: Gradle@2
    displayName: Run API Test
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean test aggregate reports'
      options: '-Dopenweathermap.api_id=<API_ID>'
    condition: and(succeededOrFailed())

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      pathToPublish: $(Build.SourcesDirectory)/target/site/serenity
      artifactName: HtmlReport
    condition: succeededOrFailed()